# Generated by Django 5.2.12 on 2026-05-16 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa', '0002_alter_pontocoleta_tipo_residuo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo_residuo', models.CharField(choices=[('domiciliar', 'Domiciliar'), ('reciclavel', 'Reciclável'), ('organico', 'Orgânico'), ('eletronico', 'Eletrônico'), ('volumoso', 'Volumoso')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ponto_coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='mapa.pontocoleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
