# Generated by Django 5.2.12 on 2026-05-18 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_pessoajuridica_bairros_atendidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.CharField(choices=[('manha', 'Manhã (06h - 12h)'), ('tarde', 'Tarde (12h - 18h)'), ('noite', 'Noite (18h - 22h)')], max_length=10)),
                ('tipo_residuo', models.CharField(choices=[('papel', 'Papel e papelão'), ('plastico', 'Plástico'), ('organico', 'Orgânico'), ('eletronico', 'Eletrônico'), ('metais', 'Metais'), ('vidro', 'Vidro')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='login.pessoajuridica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
