# Generated by Django 5.2.12 on 2026-05-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(choices=[('manha', 'Manhã (06h - 12h)'), ('tarde', 'Tarde (12h - 18h)'), ('noite', 'Noite (18h - 22h)')], max_length=10),
        ),
    ]
