# Generated by Django 5.2.12 on 2026-05-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_residuo',
            field=models.CharField(choices=[('papel', 'Papel e papelão'), ('plastico', 'Plástico'), ('organico', 'Orgânico'), ('eletronico', 'Eletrônico'), ('metais', 'Metais'), ('vidro', 'Vidro')], max_length=50),
        ),
    ]
