# Generated by Django 5.2.12 on 2026-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocoleta',
            name='tipo_residuo',
            field=models.CharField(max_length=255),
        ),
    ]
