# Generated by Django 5.2.12 on 2026-05-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='bairros_atendidos',
            field=models.CharField(blank=True, help_text='Separe os bairros por vírgula. Ex: Boa Viagem, Recife, Afogados', max_length=500),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='tipos_residuo',
            field=models.CharField(blank=True, help_text='Separe por vírgula. Ex: papel, plastico, vidro', max_length=255),
        ),
    ]
