# Generated by Django 5.2.12 on 2026-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comunidade/'),
        ),
    ]
