# Generated by Django 5.2.12 on 2026-05-18 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0003_topic_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
