# Generated by Django 5.2.12 on 2026-05-18 12:47

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0004_topic_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
    ]